name: pipeline daily for test the actual package with dependencies

on:
  schedule:
    - cron:  '13 20 * * *'

jobs:
  test:
    name: test the actual package
    runs-on: ubuntu-18.04
    steps:
      - name: install python3.6
        run: |
          sudo apt install python3.6      
      - name: update pip
        run: |
          python3 -m pip install --upgrade pip
      - name: install ytdlmusic
        run: |
          pip install ytdlmusic      
      - name: display version          
        run: |
          ytdlmusic --version
      - name: test OGG auto          
        run: |
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.ogg          
      - name: install pip
        run: |
          sudo apt-get -qq install ffmpeg          
      - name: test MP3 auto
        run: |          
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.mp3 
