name: daily pipeline

'on':
  schedule:
    - cron: "0 3 * * *"

jobs:
  test:
    name: test the actual deployed pip package with updated dependencies
    runs-on: ubuntu-18.04
    steps:
      - name: install python3.6
        run: |
          sudo apt install python3.6      
      - name: update pip
        run: |
          python3 -m pip install --upgrade pip
      - name: install ytdlmusic
        run: |
          pip install ytdlmusic      
      - name: display version          
        run: |
          ytdlmusic --version
      - name: test OGG auto          
        run: |
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.ogg          
      - name: install ffmpeg
        run: |
          sudo apt-get -qq install ffmpeg          
      - name: test MP3 auto
        run: |          
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.mp3 
