name: pipeline release for publish

on:
  release:
    types:
      - created
jobs:
  test:
    name: test and push
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install python3
        uses: actions/setup-python@v2
      - name: update pip
        run: |
          python3 -m pip install --upgrade pip
      - name: install ytdlmusic
        run: |
          pip install .      
      - name: display version          
        run: |
          ytdlmusic --version
      - name: test ogg auto          
        run: |
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.ogg          
      - name: install pip
        run: |
          sudo apt-get -qq install ffmpeg          
      - name: test mp3 auto
        run: |          
          ytdlmusic --auto "the beatles" "let it be"
          test -f the_beatles_let_it_be.mp3 
      - name: test choice
        run: |          
          yes 3 | ytdlmusic "the beatles" "let it be"
          test -f the_beatles_let_it_be_1.mp3
      - name: test diff
        run: |          
          md5sum the_beatles_let_it_be.mp3
          md5sum the_beatles_let_it_be_1.mp3
          echo "les md5 doivent etre differents"
          test "$(md5sum the_beatles_let_it_be.mp3)" != "$(md5sum the_beatles_let_it_be_1.mp3)"      
      - name: clean after test
        run: |
          rm -rf *
      - name: checkout
        uses: actions/checkout@v2          
      - name: install pep517
        run: |
          pip install pep517
      - name: build
        run: python3 -m pep517.build --source --binary --out-dir dist/ .
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
